# PowerShell script to create Career-Guidance-System DDD folder structure and placeholder files
$base = 'C:\xampp\htdocs\career-guidance-system'
$dirs = @(
"$base\App\Modules\Home\Presentation\Controllers",
"$base\App\Modules\Home\Presentation\Views",
"$base\App\Modules\Auth\Domain\Entities",
"$base\App\Modules\Auth\Domain\Repositories",
"$base\App\Modules\Auth\Application\Services",
"$base\App\Modules\Auth\Application\DTOs",
"$base\App\Modules\Auth\Infrastructure\Persistence",
"$base\App\Modules\Auth\Infrastructure\Security",
"$base\App\Modules\Auth\Presentation\Controllers",
"$base\App\Modules\Auth\Presentation\Requests",
"$base\App\Modules\Auth\Presentation\Views",
"$base\App\Modules\Student\Domain\Entities",
"$base\App\Modules\Student\Domain\Repositories",
"$base\App\Modules\Student\Application\Services",
"$base\App\Modules\Student\Application\DTOs",
"$base\App\Modules\Student\Infrastructure\Persistence",
"$base\App\Modules\Student\Presentation\Controllers",
"$base\App\Modules\Student\Presentation\Views",
"$base\App\Modules\Assessment\Domain\Entities",
"$base\App\Modules\Assessment\Domain\Repositories",
"$base\App\Modules\Assessment\Application\Services",
"$base\App\Modules\Assessment\Application\DTOs",
"$base\App\Modules\Assessment\Infrastructure\Persistence",
"$base\App\Modules\Assessment\Presentation\Controllers",
"$base\App\Modules\Assessment\Presentation\Views",
"$base\App\Modules\Result\Domain\Entities",
"$base\App\Modules\Result\Domain\Repositories",
"$base\App\Modules\Result\Application\Services",
"$base\App\Modules\Result\Application\DTOs",
"$base\App\Modules\Result\Infrastructure\Persistence",
"$base\App\Modules\Result\Presentation\Controllers",
"$base\App\Modules\Result\Presentation\Views",
"$base\App\Modules\Career\Domain\Entities",
"$base\App\Modules\Career\Domain\Repositories",
"$base\App\Modules\Career\Application\Services",
"$base\App\Modules\Career\Application\DTOs",
"$base\App\Modules\Career\Infrastructure\Persistence",
"$base\App\Modules\Career\Presentation\Controllers",
"$base\App\Modules\Career\Presentation\Views",
"$base\App\Modules\Recommendation\Domain\Entities",
"$base\App\Modules\Recommendation\Domain\Repositories",
"$base\App\Modules\Recommendation\Application\Services",
"$base\App\Modules\Recommendation\Application\DTOs",
"$base\App\Modules\Recommendation\Infrastructure\Persistence",
"$base\App\Modules\Recommendation\Presentation\Controllers",
"$base\App\Modules\Recommendation\Presentation\Views",
"$base\App\Modules\Admin\Application\Services",
"$base\App\Modules\Admin\Infrastructure\Persistence",
"$base\App\Modules\Admin\Presentation\Controllers",
"$base\App\Modules\Admin\Presentation\Views",
"$base\App\Shared\Core",
"$base\App\Shared\Helpers",
"$base\App\Shared\Middleware",
"$base\App\Shared\Exceptions",
"$base\App\config",
"$base\Public\assets\css",
"$base\Public\assets\js",
"$base\Public\assets\images",
"$base\database\migrations",
"$base\database\seeders",
"$base\vendor"
)
foreach ($d in $dirs) { New-Item -ItemType Directory -Path $d -Force | Out-Null }

$files = @(
"$base\App\Modules\Home\Presentation\Controllers\HomeController.php",
"$base\App\Modules\Home\Presentation\Views\home.php",
"$base\App\Modules\Home\Presentation\Views\about.php",
"$base\App\Modules\Home\Presentation\Views\contact.php",

"$base\App\Modules\Auth\Domain\Entities\User.php",
"$base\App\Modules\Auth\Domain\Repositories\UserRepositoryInterface.php",
"$base\App\Modules\Auth\Application\Services\AuthService.php",
"$base\App\Modules\Auth\Application\DTOs\RegisterStudentDTO.php",
"$base\App\Modules\Auth\Application\DTOs\LoginDTO.php",
"$base\App\Modules\Auth\Infrastructure\Persistence\UserRepository.php",
"$base\App\Modules\Auth\Infrastructure\Security\PasswordHasher.php",
"$base\App\Modules\Auth\Presentation\Controllers\AuthController.php",
"$base\App\Modules\Auth\Presentation\Requests\RegisterRequest.php",
"$base\App\Modules\Auth\Presentation\Requests\LoginRequest.php",
"$base\App\Modules\Auth\Presentation\Views\register.php",
"$base\App\Modules\Auth\Presentation\Views\login.php",

"$base\App\Modules\Student\Domain\Entities\StudentProfile.php",
"$base\App\Modules\Student\Domain\Repositories\StudentProfileRepositoryInterface.php",
"$base\App\Modules\Student\Application\Services\StudentService.php",
"$base\App\Modules\Student\Application\DTOs\UpdateStudentProfileDTO.php",
"$base\App\Modules\Student\Infrastructure\Persistence\StudentProfileRepository.php",
"$base\App\Modules\Student\Presentation\Controllers\StudentController.php",
"$base\App\Modules\Student\Presentation\Views\dashboard.php",
"$base\App\Modules\Student\Presentation\Views\profile.php",

"$base\App\Modules\Assessment\Domain\Entities\Assessment.php",
"$base\App\Modules\Assessment\Domain\Entities\Question.php",
"$base\App\Modules\Assessment\Domain\Entities\QuestionOption.php",
"$base\App\Modules\Assessment\Domain\Entities\StudentAssessment.php",
"$base\App\Modules\Assessment\Domain\Entities\StudentAnswer.php",
"$base\App\Modules\Assessment\Domain\Repositories\AssessmentRepositoryInterface.php",
"$base\App\Modules\Assessment\Domain\Repositories\QuestionRepositoryInterface.php",
"$base\App\Modules\Assessment\Domain\Repositories\QuestionOptionRepositoryInterface.php",
"$base\App\Modules\Assessment\Domain\Repositories\StudentAssessmentRepositoryInterface.php",
"$base\App\Modules\Assessment\Domain\Repositories\StudentAnswerRepositoryInterface.php",
"$base\App\Modules\Assessment\Application\Services\AssessmentService.php",
"$base\App\Modules\Assessment\Application\DTOs\StartAssessmentDTO.php",
"$base\App\Modules\Assessment\Application\DTOs\SaveStudentAnswerDTO.php",
"$base\App\Modules\Assessment\Application\DTOs\SubmitAssessmentDTO.php",
"$base\App\Modules\Assessment\Infrastructure\Persistence\AssessmentRepository.php",
"$base\App\Modules\Assessment\Infrastructure\Persistence\QuestionRepository.php",
"$base\App\Modules\Assessment\Infrastructure\Persistence\QuestionOptionRepository.php",
"$base\App\Modules\Assessment\Infrastructure\Persistence\StudentAssessmentRepository.php",
"$base\App\Modules\Assessment\Infrastructure\Persistence\StudentAnswerRepository.php",
"$base\App\Modules\Assessment\Presentation\Controllers\AssessmentController.php",
"$base\App\Modules\Assessment\Presentation\Views\assessment-list.php",
"$base\App\Modules\Assessment\Presentation\Views\take-assessment.php",
"$base\App\Modules\Assessment\Presentation\Views\assessment-progress.php",

"$base\App\Modules\Result\Domain\Entities\AssessmentResult.php",
"$base\App\Modules\Result\Domain\Repositories\ResultRepositoryInterface.php",
"$base\App\Modules\Result\Application\Services\ResultService.php",
"$base\App\Modules\Result\Application\DTOs\ResultFilterDTO.php",
"$base\App\Modules\Result\Infrastructure\Persistence\ResultRepository.php",
"$base\App\Modules\Result\Presentation\Controllers\ResultController.php",
"$base\App\Modules\Result\Presentation\Views\results.php",
"$base\App\Modules\Result\Presentation\Views\result-details.php",

"$base\App\Modules\Career\Domain\Entities\Career.php",
"$base\App\Modules\Career\Domain\Entities\CareerCategory.php",
"$base\App\Modules\Career\Domain\Repositories\CareerRepositoryInterface.php",
"$base\App\Modules\Career\Domain\Repositories\CareerCategoryRepositoryInterface.php",
"$base\App\Modules\Career\Application\Services\CareerService.php",
"$base\App\Modules\Career\Application\DTOs\CareerSearchDTO.php",
"$base\App\Modules\Career\Infrastructure\Persistence\CareerRepository.php",
"$base\App\Modules\Career\Infrastructure\Persistence\CareerCategoryRepository.php",
"$base\App\Modules\Career\Presentation\Controllers\CareerController.php",
"$base\App\Modules\Career\Presentation\Views\careers.php",
"$base\App\Modules\Career\Presentation\Views\career-details.php",

"$base\App\Modules\Recommendation\Domain\Entities\CareerRecommendation.php",
"$base\App\Modules\Recommendation\Domain\Repositories\RecommendationRepositoryInterface.php",
"$base\App\Modules\Recommendation\Application\Services\RecommendationService.php",
"$base\App\Modules\Recommendation\Application\DTOs\RecommendationDTO.php",
"$base\App\Modules\Recommendation\Infrastructure\Persistence\RecommendationRepository.php",
"$base\App\Modules\Recommendation\Presentation\Controllers\RecommendationController.php",
"$base\App\Modules\Recommendation\Presentation\Views\recommendations.php",

"$base\App\Modules\Admin\Application\Services\AdminService.php",
"$base\App\Modules\Admin\Infrastructure\Persistence\AdminRepository.php",
"$base\App\Modules\Admin\Presentation\Controllers\AdminController.php",
"$base\App\Modules\Admin\Presentation\Views\dashboard.php",
"$base\App\Modules\Admin\Presentation\Views\students.php",
"$base\App\Modules\Admin\Presentation\Views\assessments.php",
"$base\App\Modules\Admin\Presentation\Views\careers.php",
"$base\App\Modules\Admin\Presentation\Views\results.php",

"$base\App\Shared\Core\Database.php",
"$base\App\Shared\Core\BaseController.php",
"$base\App\Shared\Core\BaseRepository.php",
"$base\App\Shared\Core\Router.php",
"$base\App\Shared\Core\View.php",

"$base\App\Shared\Helpers\redirect.php",
"$base\App\Shared\Helpers\auth.php",
"$base\App\Shared\Helpers\response.php",

"$base\App\Shared\Middleware\AuthMiddleware.php",
"$base\App\Shared\Middleware\GuestMiddleware.php",
"$base\App\Shared\Middleware\AdminMiddleware.php",

"$base\App\Shared\Exceptions\NotFoundException.php",
"$base\App\Shared\Exceptions\ValidationException.php",

"$base\App\config\app.php",

"$base\Public\index.php",
"$base\Public\assets\css\.gitkeep",
"$base\Public\assets\js\.gitkeep",
"$base\Public\assets\images\.gitkeep",

"$base\database\migrations\.gitkeep",
"$base\database\seeders\.gitkeep",
"$base\database\career_guidance.sql",

"$base\\.env"
)
foreach ($f in $files) {
 $dir = Split-Path $f -Parent
 if(-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
 if(-not (Test-Path $f)) { Set-Content -Path $f -Value "<?php`n// placeholder file: $(Split-Path $f -Leaf)" -Encoding UTF8 }
}
Write-Host 'Structure created.'
