<?php

namespace App\Modules\Career\Presentation\Controllers;

use App\Shared\Core\View;

class CareerController
{
    private array $careers = [
        'software-engineer' => [
            'name' => 'Software Engineer',
            'category' => 'Technology',
            'icon' => 'fa-code',
            'color' => 'indigo',
            'high_demand' => true,
            'description' => 'Design, develop, and maintain software systems that power businesses and improve everyday life through code.',
            'about' => 'Software engineering is the disciplined approach to designing, developing, testing, and maintaining software applications. Software engineers apply engineering principles and programming expertise to create reliable and efficient software solutions that solve real-world problems across industries.',
            'skills' => ['Programming', 'Problem Solving', 'System Design', 'Debugging', 'Version Control', 'Team Collaboration'],
            'education' => "Bachelor\u2019s Degree in Computer Science or related field",
            'certification' => 'Optional: AWS Certified Developer or Google Professional Cloud Developer',
            'work_environment' => [
                ['place' => 'Tech Offices', 'icon' => 'fa-building'],
                ['place' => 'Remote Work', 'icon' => 'fa-laptop-house'],
                ['place' => 'Tech Hubs', 'icon' => 'fa-city'],
                ['place' => 'Startups', 'icon' => 'fa-rocket'],
            ],
            'salary_min' => 1500000,
            'salary_max' => 5000000,
            'job_outlook' => 'High',
            'right_for_you' => [
                'You enjoy solving complex problems',
                'You like building and creating things',
                'You have strong analytical skills',
                'You enjoy continuous learning',
            ],
            'related' => ['data-analyst', 'ux-designer', 'civil-engineer'],
        ],
        'data-analyst' => [
            'name' => 'Data Analyst',
            'category' => 'Technology',
            'icon' => 'fa-database',
            'color' => 'indigo',
            'high_demand' => true,
            'description' => 'Interpret complex datasets, generate actionable insights, and support data-driven decision-making across organizations.',
            'about' => 'Data analysis involves collecting, processing, and performing statistical analyses on large datasets to discover meaningful patterns and insights. Data analysts help organizations make informed decisions by transforming raw data into clear, actionable reports and visualizations.',
            'skills' => ['Data Visualization', 'SQL', 'Statistical Analysis', 'Critical Thinking', 'Excel', 'Python/R'],
            'education' => "Bachelor\u2019s Degree in Data Science, Statistics, or related field",
            'certification' => 'Optional: Google Data Analytics Professional Certificate',
            'work_environment' => [
                ['place' => 'Corporate Offices', 'icon' => 'fa-building'],
                ['place' => 'Remote Work', 'icon' => 'fa-laptop-house'],
                ['place' => 'Tech Companies', 'icon' => 'fa-city'],
                ['place' => 'Research Labs', 'icon' => 'fa-flask'],
            ],
            'salary_min' => 1200000,
            'salary_max' => 3500000,
            'job_outlook' => 'High',
            'right_for_you' => [
                'You enjoy working with numbers and data',
                'You like finding patterns and insights',
                'You have strong attention to detail',
                'You enjoy communicating findings to others',
            ],
            'related' => ['software-engineer', 'financial-analyst', 'marketing-manager'],
        ],
        'doctor' => [
            'name' => 'Doctor',
            'category' => 'Healthcare',
            'icon' => 'fa-stethoscope',
            'color' => 'emerald',
            'high_demand' => false,
            'description' => 'Diagnose and treat illnesses, provide preventive care, and educate patients on maintaining their health.',
            'about' => 'Doctors are medical professionals who diagnose and treat injuries and illnesses. They examine patients, take medical histories, prescribe medications, and order diagnostic tests. Doctors also provide preventive care and health education to help patients maintain their well-being.',
            'skills' => ['Diagnosis', 'Patient Care', 'Medical Knowledge', 'Communication', 'Attention to Detail', 'Empathy'],
            'education' => "Doctor of Medicine (MD) degree and licensed medical residency",
            'certification' => 'Required: Medical License from Myanmar Medical Council',
            'work_environment' => [
                ['place' => 'Hospitals', 'icon' => 'fa-hospital'],
                ['place' => 'Clinics', 'icon' => 'fa-clinic-medical'],
                ['place' => 'Private Practice', 'icon' => 'fa-user-md'],
                ['place' => 'Research Labs', 'icon' => 'fa-flask'],
            ],
            'salary_min' => 2000000,
            'salary_max' => 6000000,
            'job_outlook' => 'High',
            'right_for_you' => [
                'You have a strong desire to help others',
                'You can handle high-pressure situations',
                'You enjoy science and continuous learning',
                'You have excellent communication skills',
            ],
            'related' => ['nurse', 'teacher', 'professor'],
        ],
        'nurse' => [
            'name' => 'Nurse',
            'category' => 'Healthcare',
            'icon' => 'fa-heartbeat',
            'color' => 'emerald',
            'high_demand' => true,
            'description' => 'Provide compassionate patient care, administer treatments, and collaborate with medical teams in clinical settings.',
            'about' => 'Nursing is a healthcare profession focused on caring for individuals and communities to maintain or improve their health. Nurses work alongside doctors, administer medications, monitor patient progress, and provide emotional support to patients and their families.',
            'skills' => ['Patient Care', 'Clinical Skills', 'Communication', 'Compassion', 'Critical Thinking', 'Teamwork'],
            'education' => "Bachelor of Science in Nursing (BSN) and nursing license",
            'certification' => 'Required: Nursing License from Myanmar Nursing Council',
            'work_environment' => [
                ['place' => 'Hospitals', 'icon' => 'fa-hospital'],
                ['place' => 'Clinics', 'icon' => 'fa-clinic-medical'],
                ['place' => 'Nursing Homes', 'icon' => 'fa-home'],
                ['place' => 'Community Health', 'icon' => 'fa-people-arrows'],
            ],
            'salary_min' => 800000,
            'salary_max' => 2500000,
            'job_outlook' => 'High',
            'right_for_you' => [
                'You are compassionate and caring',
                'You work well in a team environment',
                'You can stay calm under pressure',
                'You enjoy helping people every day',
            ],
            'related' => ['doctor', 'teacher', 'business-analyst'],
        ],
        'accountant' => [
            'name' => 'Accountant',
            'category' => 'Finance',
            'icon' => 'fa-calculator',
            'color' => 'blue',
            'high_demand' => false,
            'description' => 'Prepare financial records, ensure tax compliance, and provide strategic financial guidance to organizations.',
            'about' => 'Accountants are responsible for maintaining and auditing financial records, ensuring compliance with tax laws and regulations, and providing strategic financial advice. They play a crucial role in helping businesses and individuals manage their finances effectively and make informed economic decisions.',
            'skills' => ['Financial Reporting', 'Tax Knowledge', 'Attention to Detail', 'Analytical Skills', 'Ethics', 'Software Proficiency'],
            'education' => "Bachelor\u2019s Degree in Accounting or Finance",
            'certification' => 'Optional: CPA (Certified Public Accountant) or ACCA',
            'work_environment' => [
                ['place' => 'Corporate Offices', 'icon' => 'fa-building'],
                ['place' => 'Audit Firms', 'icon' => 'fa-briefcase'],
                ['place' => 'Remote Work', 'icon' => 'fa-laptop-house'],
                ['place' => 'Financial Institutions', 'icon' => 'fa-university'],
            ],
            'salary_min' => 1000000,
            'salary_max' => 3000000,
            'job_outlook' => 'Medium',
            'right_for_you' => [
                'You are detail-oriented and organized',
                'You enjoy working with numbers',
                'You have strong ethical standards',
                'You like structured and methodical work',
            ],
            'related' => ['financial-analyst', 'business-analyst', 'marketing-manager'],
        ],
        'financial-analyst' => [
            'name' => 'Financial Analyst',
            'category' => 'Finance',
            'icon' => 'fa-chart-bar',
            'color' => 'blue',
            'high_demand' => false,
            'description' => 'Analyze financial data, prepare reports, and guide investment decisions to maximize organizational profitability.',
            'about' => 'Financial analysts evaluate investment opportunities, analyze economic trends, and provide guidance to businesses and individuals making investment decisions. They study financial statements, assess company performance, and create financial models to forecast future business outcomes.',
            'skills' => ['Financial Modeling', 'Data Analysis', 'Investment Knowledge', 'Excel', 'Report Writing', 'Decision Making'],
            'education' => "Bachelor\u2019s Degree in Finance, Economics, or related field",
            'certification' => 'Optional: CFA (Chartered Financial Analyst) certification',
            'work_environment' => [
                ['place' => 'Banks', 'icon' => 'fa-university'],
                ['place' => 'Corporate Offices', 'icon' => 'fa-building'],
                ['place' => 'Investment Firms', 'icon' => 'fa-chart-line'],
                ['place' => 'Remote Work', 'icon' => 'fa-laptop-house'],
            ],
            'salary_min' => 1500000,
            'salary_max' => 4000000,
            'job_outlook' => 'Medium',
            'right_for_you' => [
                'You enjoy analyzing markets and trends',
                'You like making data-driven decisions',
                'You have strong mathematical skills',
                'You are interested in the economy',
            ],
            'related' => ['accountant', 'business-analyst', 'data-analyst'],
        ],
        'civil-engineer' => [
            'name' => 'Civil Engineer',
            'category' => 'Engineering',
            'icon' => 'fa-hard-hat',
            'color' => 'cyan',
            'high_demand' => true,
            'description' => 'Plan, design, and oversee construction of infrastructure projects such as roads, bridges, and buildings.',
            'about' => 'Civil engineering is a professional discipline that deals with the design, construction, and maintenance of the built environment. Civil engineers plan and oversee infrastructure projects including roads, bridges, dams, airports, and buildings, ensuring they are safe, sustainable, and cost-effective.',
            'skills' => ['Structural Design', 'Project Management', 'AutoCAD', 'Surveying', 'Problem Solving', 'Team Leadership'],
            'education' => "Bachelor\u2019s Degree in Civil Engineering",
            'certification' => 'Optional: Professional Engineer (PE) license',
            'work_environment' => [
                ['place' => 'Construction Sites', 'icon' => 'fa-hard-hat'],
                ['place' => 'Design Offices', 'icon' => 'fa-building'],
                ['place' => 'Government Agencies', 'icon' => 'fa-landmark'],
                ['place' => 'Consulting Firms', 'icon' => 'fa-handshake'],
            ],
            'salary_min' => 1200000,
            'salary_max' => 4000000,
            'job_outlook' => 'High',
            'right_for_you' => [
                'You enjoy designing and building structures',
                'You like working on large-scale projects',
                'You have strong problem-solving skills',
                'You enjoy working both indoors and outdoors',
            ],
            'related' => ['mechanical-engineer', 'software-engineer', 'business-analyst'],
        ],
        'mechanical-engineer' => [
            'name' => 'Mechanical Engineer',
            'category' => 'Engineering',
            'icon' => 'fa-cogs',
            'color' => 'cyan',
            'high_demand' => true,
            'description' => 'Design and develop mechanical systems, from innovative product prototypes to large-scale industrial machinery.',
            'about' => 'Mechanical engineering applies physics and materials science principles to design, analyze, and manufacture mechanical systems. Mechanical engineers work on everything from tiny components like sensors to large systems like spacecraft, creating solutions that improve how we live and work.',
            'skills' => ['CAD Design', 'Thermodynamics', 'Manufacturing', 'Problem Solving', 'Mathematics', 'Innovation'],
            'education' => "Bachelor\u2019s Degree in Mechanical Engineering",
            'certification' => 'Optional: Professional Engineer (PE) license',
            'work_environment' => [
                ['place' => 'Factories', 'icon' => 'fa-industry'],
                ['place' => 'Design Workshops', 'icon' => 'fa-tools'],
                ['place' => 'Corporate Offices', 'icon' => 'fa-building'],
                ['place' => 'Research Labs', 'icon' => 'fa-flask'],
            ],
            'salary_min' => 1300000,
            'salary_max' => 4500000,
            'job_outlook' => 'High',
            'right_for_you' => [
                'You enjoy understanding how machines work',
                'You like designing and improving products',
                'You have strong physics and math skills',
                'You enjoy hands-on problem solving',
            ],
            'related' => ['civil-engineer', 'software-engineer', 'teacher'],
        ],
        'teacher' => [
            'name' => 'Teacher',
            'category' => 'Education',
            'icon' => 'fa-chalkboard-teacher',
            'color' => 'purple',
            'high_demand' => false,
            'description' => 'Educate and inspire students, develop curricula, and foster a positive learning environment for academic growth.',
            'about' => 'Teachers play a vital role in shaping the future by educating and mentoring students. They develop lesson plans, assess student progress, create engaging learning environments, and inspire curiosity and a love for learning. Teachers work in schools, colleges, and other educational settings.',
            'skills' => ['Lesson Planning', 'Classroom Management', 'Communication', 'Patience', 'Adaptability', 'Mentoring'],
            'education' => "Bachelor\u2019s Degree in Education or specialized subject area",
            'certification' => 'Required: Teaching License from Ministry of Education',
            'work_environment' => [
                ['place' => 'Schools', 'icon' => 'fa-school'],
                ['place' => 'Colleges', 'icon' => 'fa-university'],
                ['place' => 'Online Platforms', 'icon' => 'fa-laptop'],
                ['place' => 'Tutoring Centers', 'icon' => 'fa-chalkboard-teacher'],
            ],
            'salary_min' => 500000,
            'salary_max' => 1500000,
            'job_outlook' => 'Medium',
            'right_for_you' => [
                'You enjoy teaching and mentoring others',
                'You have strong communication skills',
                'You are patient and understanding',
                'You like making a difference in students\u2019 lives',
            ],
            'related' => ['professor', 'nurse', 'graphic-designer'],
        ],
        'professor' => [
            'name' => 'Professor',
            'category' => 'Education',
            'icon' => 'fa-graduation-cap',
            'color' => 'purple',
            'high_demand' => false,
            'description' => 'Teach at the university level, conduct research, and mentor students in advanced academic and professional fields.',
            'about' => 'Professors are educators and researchers at colleges and universities who teach undergraduate and graduate courses, conduct scholarly research, publish academic papers, and mentor students in their academic and professional development. They are experts in their specialized fields.',
            'skills' => ['Research', 'Public Speaking', 'Writing', 'Mentoring', 'Curriculum Design', 'Critical Analysis'],
            'education' => "Doctoral degree (PhD) in specialized field",
            'certification' => 'Optional: Postdoctoral research experience',
            'work_environment' => [
                ['place' => 'Universities', 'icon' => 'fa-university'],
                ['place' => 'Research Centers', 'icon' => 'fa-flask'],
                ['place' => 'Online Academia', 'icon' => 'fa-laptop'],
                ['place' => 'Conference Halls', 'icon' => 'fa-microphone'],
            ],
            'salary_min' => 1500000,
            'salary_max' => 4000000,
            'job_outlook' => 'Medium',
            'right_for_you' => [
                'You are passionate about your field of study',
                'You enjoy teaching and mentoring students',
                'You like conducting research and publishing',
                'You have strong public speaking skills',
            ],
            'related' => ['teacher', 'doctor', 'software-engineer'],
        ],
        'marketing-manager' => [
            'name' => 'Marketing Manager',
            'category' => 'Business',
            'icon' => 'fa-chart-line',
            'color' => 'orange',
            'high_demand' => false,
            'description' => 'Develop marketing strategies, oversee campaigns, and drive brand growth through market research and creative initiatives.',
            'about' => 'Marketing managers plan and execute marketing strategies to promote products, services, or brands. They conduct market research, coordinate advertising campaigns, manage budgets, analyze consumer trends, and lead marketing teams to drive business growth and brand awareness.',
            'skills' => ['Strategic Planning', 'Digital Marketing', 'Market Research', 'Leadership', 'Analytics', 'Creativity'],
            'education' => "Bachelor\u2019s Degree in Marketing, Business, or related field",
            'certification' => 'Optional: Google Digital Marketing Certification',
            'work_environment' => [
                ['place' => 'Corporate Offices', 'icon' => 'fa-building'],
                ['place' => 'Advertising Agencies', 'icon' => 'fa-bullhorn'],
                ['place' => 'Remote Work', 'icon' => 'fa-laptop-house'],
                ['place' => 'Media Houses', 'icon' => 'fa-tv'],
            ],
            'salary_min' => 1500000,
            'salary_max' => 5000000,
            'job_outlook' => 'Medium',
            'right_for_you' => [
                'You are creative and strategic',
                'You enjoy leading campaigns and teams',
                'You have strong communication skills',
                'You like analyzing consumer behavior',
            ],
            'related' => ['business-analyst', 'graphic-designer', 'accountant'],
        ],
        'business-analyst' => [
            'name' => 'Business Analyst',
            'category' => 'Business',
            'icon' => 'fa-briefcase',
            'color' => 'indigo',
            'high_demand' => false,
            'description' => 'Analyze business processes, identify improvement opportunities, and bridge the gap between IT and business stakeholders.',
            'about' => 'Business analysts help organizations improve their processes, systems, and workflows. They analyze business needs, gather requirements, identify solutions, and bridge communication between business stakeholders and technical teams to drive successful project outcomes.',
            'skills' => ['Requirements Gathering', 'Process Modeling', 'Data Analysis', 'Communication', 'Problem Solving', 'Stakeholder Management'],
            'education' => "Bachelor\u2019s Degree in Business Administration or related field",
            'certification' => 'Optional: CBAP (Certified Business Analysis Professional)',
            'work_environment' => [
                ['place' => 'Corporate Offices', 'icon' => 'fa-building'],
                ['place' => 'IT Departments', 'icon' => 'fa-server'],
                ['place' => 'Remote Work', 'icon' => 'fa-laptop-house'],
                ['place' => 'Consulting Firms', 'icon' => 'fa-handshake'],
            ],
            'salary_min' => 1200000,
            'salary_max' => 3500000,
            'job_outlook' => 'High',
            'right_for_you' => [
                'You enjoy solving business problems',
                'You like bridging technology and business',
                'You have strong analytical skills',
                'You enjoy working with diverse teams',
            ],
            'related' => ['accountant', 'financial-analyst', 'marketing-manager'],
        ],
        'ux-designer' => [
            'name' => 'UX Designer',
            'category' => 'Creative Arts',
            'icon' => 'fa-paint-brush',
            'color' => 'orange',
            'high_demand' => false,
            'description' => 'Craft intuitive user experiences by researching user needs and designing accessible, visually engaging interfaces.',
            'about' => 'UX design focuses on creating meaningful and accessible experiences for users of digital products. UX designers research user needs, design wireframes and prototypes, conduct usability testing, and collaborate with developers to create interfaces that are intuitive, efficient, and enjoyable to use.',
            'skills' => ['User Research', 'Wireframing', 'Prototyping', 'Visual Design', 'Usability Testing', 'Figma/Sketch'],
            'education' => "Bachelor\u2019s Degree in Design, HCI, or related field",
            'certification' => 'Optional: Google UX Design Professional Certificate',
            'work_environment' => [
                ['place' => 'Tech Companies', 'icon' => 'fa-city'],
                ['place' => 'Design Agencies', 'icon' => 'fa-palette'],
                ['place' => 'Remote Work', 'icon' => 'fa-laptop-house'],
                ['place' => 'Startups', 'icon' => 'fa-rocket'],
            ],
            'salary_min' => 1500000,
            'salary_max' => 4500000,
            'job_outlook' => 'Medium',
            'right_for_you' => [
                'You enjoy designing user-friendly interfaces',
                'You like understanding user behavior',
                'You have a creative and analytical mind',
                'You enjoy collaborating with developers',
            ],
            'related' => ['graphic-designer', 'software-engineer', 'marketing-manager'],
        ],
        'graphic-designer' => [
            'name' => 'Graphic Designer',
            'category' => 'Creative Arts',
            'icon' => 'fa-palette',
            'color' => 'pink',
            'high_demand' => false,
            'description' => 'Create compelling visual content for brands, marketing campaigns, and digital media using design tools.',
            'about' => 'Graphic designers use visual elements like typography, color, imagery, and layout to communicate ideas and messages. They create designs for branding, advertising, websites, social media, and print materials, combining artistic talent with technical skills to produce visually appealing content.',
            'skills' => ['Adobe Creative Suite', 'Typography', 'Color Theory', 'Branding', 'Illustration', 'Layout Design'],
            'education' => "Bachelor\u2019s Degree in Graphic Design or Visual Arts",
            'certification' => 'Optional: Adobe Certified Professional',
            'work_environment' => [
                ['place' => 'Design Studios', 'icon' => 'fa-palette'],
                ['place' => 'Ad Agencies', 'icon' => 'fa-bullhorn'],
                ['place' => 'Remote Work', 'icon' => 'fa-laptop-house'],
                ['place' => 'Publishing Houses', 'icon' => 'fa-book'],
            ],
            'salary_min' => 800000,
            'salary_max' => 2500000,
            'job_outlook' => 'Medium',
            'right_for_you' => [
                'You have a strong creative vision',
                'You enjoy visual communication',
                'You are detail-oriented with design',
                'You like bringing ideas to life visually',
            ],
            'related' => ['ux-designer', 'marketing-manager', 'teacher'],
        ],
    ];

    public function index(): void
    {
        View::render('Career/Presentation/Views/careers', [
            'pageTitle' => 'Explore Careers - Career Guidance System'
        ]);
    }

    public function show(): void
    {
        $slug = (string)($_GET['id'] ?? '');

        if ($slug === '' || !isset($this->careers[$slug])) {
            header('Location: ' . ($_ENV['BASE_URL'] ?? '') . '/index.php?page=careers');
            exit;
        }

        $career = $this->careers[$slug];

        $relatedCareers = [];
        foreach ($career['related'] as $relatedSlug) {
            if (isset($this->careers[$relatedSlug])) {
                $relatedCareers[$relatedSlug] = $this->careers[$relatedSlug];
            }
        }

        View::render('Career/Presentation/Views/career-detail', [
            'pageTitle' => $career['name'] . ' - Career Guidance System',
            'career' => $career,
            'slug' => $slug,
            'relatedCareers' => $relatedCareers,
        ]);
    }
}